#!name=国外广告拦截规则集
#!desc=某些规则要清除缓存或者重新安装APP，拦截广告才会生效！
#AdBlock_Overseas
#Update time: 2026-06-19

[Rule]
# Apple
DOMAIN-SUFFIX,advertising.apple.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,api-adservices.apple.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,iadsdk.apple.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,iad.apple.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,qwapi.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,analytics.edge.apple,REJECT,extended-matching,pre-matching
# Adobe
DOMAIN-SUFFIX,advertising.adobe.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,tubemogul.com,REJECT,extended-matching,pre-matching
# Amazon
DOMAIN-SUFFIX,amazon-adsystem.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,serving-sys.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,advertising-api-fe.amazon.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,advertising-api.amazon.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,advertising-api-eu.amazon.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,s.amazon-adsystem.com,REJECT,extended-matching,pre-matching
# Duolingo
DOMAIN-SUFFIX,ads-api.duolingo.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,analytics.vpc.duolingo.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,metrics.duolingo.com,REJECT,extended-matching,pre-matching
# Google
DOMAIN-SUFFIX,2mdn-cn.net,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,2mdn.net,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,admob-cn.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,admob.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,adsense.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,adsensecustomsearchads.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,adsenseformobileapps.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,adservice.google.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,adtrafficquality.google,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,advertisercommunity.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,advertiserscommunity.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,adwords-community.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,adwords.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,adwordsexpress.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,analytics-alv.google.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,app-analytics-services.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,app-analytics-services-att.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,app-measurement-cn.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,app-measurement.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,doubleclick-cn.net,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,doubleclick.cn,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,doubleclick.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,doubleclick.net,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,ad.doubleclick.net,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,fls.doubleclick.net,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,cm.g.doubleclick.net,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,safeframe.googlesyndication.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,static.googleadsserving.cn,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,fcmatch.google.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,google-analytics-cn.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,google-analytics.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,googleadapis.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,googleadapis.l.google.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,googleads-cn.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,googleads.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,googleadservices-cn.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,googleadservices.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,googleadsserving.cn,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,googleanalytics.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,googleoptimize-cn.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,googleoptimize.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,googlesyndication-cn.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,googlesyndication.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,googletagmanager-cn.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,googletagmanager.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,googletagservices-cn.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,googletagservices.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,googletraveladservices-cn.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,googletraveladservices.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,googlevads-cn.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,mail-ads.google.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,mobileads.google.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,marketingplatform.google.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,pagead.l.google.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,partnerad.l.google.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,urchin.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,analytics.google.com,REJECT,extended-matching,pre-matching
# Youtube
DOMAIN-SUFFIX,ads.youtube.com,REJECT,extended-matching,pre-matching
# Microsoft
DOMAIN-SUFFIX,clarity.ms,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,microsoftads.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,msads.net,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,nelreports.net,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,adsdk.bing.net,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,bingads.microsoft.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,adsdk.microsoft.com,REJECT,extended-matching,pre-matching
# MSN
DOMAIN-SUFFIX,browser.events.data.msn.cn,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,browser.events.data.msn.com,REJECT,extended-matching,pre-matching
# Meta
# Facebook
DOMAIN-SUFFIX,analytics.facebook.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,facebookads.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,pixel.facebook.com,REJECT,extended-matching,pre-matching
#DOMAIN-SUFFIX,ep2.facebook.com,REJECT,extended-matching,pre-matching
#DOMAIN-SUFFIX,ep7.facebook.com,REJECT,extended-matching,pre-matching
DOMAIN-WILDCARD,ep*.facebook.com,REJECT,extended-matching,pre-matching
# Instagram
#DOMAIN-SUFFIX,graph.instagram.com,REJECT,extended-matching,pre-matching
#DOMAIN-SUFFIX,graph-fallback.instagram.com,REJECT,extended-matching,pre-matching
# WhatsApp
#DOMAIN-SUFFIX,graph.whatsapp.com,REJECT,extended-matching,pre-matching
#DOMAIN-SUFFIX,graph.whatsapp.net,REJECT,extended-matching,pre-matching
# OpenAI
DOMAIN-SUFFIX,chatgpt.livekit.cloud,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,host.livekit.cloud,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,turn.livekit.cloud,REJECT,extended-matching,pre-matching
# Spotify
DOMAIN-SUFFIX,adeventtracker.spotify.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,adstudio-assets.scdn.co,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,bloodhound.spotify.com,REJECT,extended-matching,pre-matching
# Twitter
DOMAIN-SUFFIX,ads-twitter.com,REJECT,extended-matching,pre-matching
# TikTok
DOMAIN-SUFFIX,analytics.tiktok.com,REJECT,extended-matching,pre-matching
# Unity
DOMAIN-SUFFIX,iads.unity3d.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,unityads.unity3d.com,REJECT,extended-matching,pre-matching
# UnityChina
DOMAIN-SUFFIX,ads.unitychina.cn,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,splash-ads.cdn.unity.cn,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,splash-ads.unitychina.cn,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,unityads.unity.cn,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,unityads.unitychina.cn,REJECT,extended-matching,pre-matching
# Yahoo
DOMAIN-SUFFIX,ads.yahoo.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,gemini.yahoo.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,ysm.yahoo.com,REJECT,extended-matching,pre-matching
# Yandex
DOMAIN-SUFFIX,adfox.ru,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,adfox.yandex.ru,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,admetrica.ru,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,ads.yandex,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,ads.yandex.ru,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,adv.yandex.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,adv.yandex.ru,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,an.yandex.ru,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,appmetrica.yandex.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,appmetrica.yandex.net,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,appmetrica.yandex.ru,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,appmetrica.yango.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,bs.yandex.ru,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,clck.yandex.ru,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,counter.yandex.ru,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,mc.yandex.ru,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,metrika.yandex.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,metrika.yandex.net,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,metrika.yandex.ru,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,webvisor.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,webvisor.org,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,yabs.yandex.ru,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,yads.tech,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,yandex-metrica.ru,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,yandexmetrica.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,yango-ads.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,adfstat.yandex.ru,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,ads.yandex.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,ads.yango.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,adsdk.yandex.ru,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,amc.yandex.ru,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,analytics.mobile.yandex.net,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,clck.yandex.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,clck.yandex.net,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,clck.yango.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,informer.yandex.ru,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,mc.yandex.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,mc.yandex.net,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,mc.yango.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,pixel.yandex.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,report.ap.yandex-net.ru,REJECT,extended-matching,pre-matching
# 通用广告联盟+跟踪器
DOMAIN-SUFFIX,scorecardresearch.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,criteo.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,cloudfront.net,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,adsafeprotected.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,zedo.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,quantserve.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,trustarc.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,adform.net,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,flurry.com,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,tracking-protection.cdn.mozilla.net,REJECT,extended-matching,pre-matching