#!name=国内广告拦截规则集
#!desc=某些规则要清除缓存或者重新安装APP，拦截广告才会生效！
#AdBlock_Local
#Update time: 2026-07-04

[Rule]
# Alibaba
DOMAIN-SUFFIX,track.alicdn.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,wgo.mmstat.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,g-adashx.ut.taobao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,a.alimama.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adash-c.m.taobao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adash-c.ut.taobao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adash.m.taobao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adashbc.m.taobao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adashbc.ut.taobao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adashx.m.taobao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adashx4ae.ut.taobao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adashx4yt.m.taobao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adashxgc.ut.taobao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adsh.m.taobao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adtrack.quark.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,c-adash.m.taobao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,fourier.taobao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,g.click.taobao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,h-adashx.ut.taobao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,h-adashx4yt.ut.taobao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,m-adash.m.taobao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,marketing.alibaba.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,nbsdk-baichuan.taobao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,retcode.taobao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,tns.simba.taobao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,track.lc.quark.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,v6-adashx.ut.taobao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,v6-adashx.ut.cainiao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,open-adash.alipay.com,REJECT-DROP,extended-matching,pre-matching
# Aliyun
DOMAIN-SUFFIX,acjs.aliyun.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adash-emas.cn-hangzhou.aliyuncs.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,m-adash.cn-hangzhou.log.aliyuncs.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adash.man.aliyuncs.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,alimama.alicdn.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,atanx.alicdn.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,atanx2.alicdn.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,baichuan-sdk.alicdn.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,nbsdk-baichuan.alicdn.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,tce.alicdn.com,REJECT-DROP,extended-matching,pre-matching
# Baidu
DOMAIN-SUFFIX,adscdn.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adx.xiaodutv.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,afd.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,afdconf.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,baifen.music.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,bzclk.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,cb.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,cbjs.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,cm.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,cpro.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,cpro2.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-WILDCARD,cpro.*.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-WILDCARD,cpro*.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-WILDCARD,cpro*.baidustatic.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,cpro.tieba.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,cpro.baidustatic.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,cpu.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,cstm.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,dlswbr.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,drmcmm.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,duiwai.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,dup.baidustatic.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,eclick.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ecma.bdimg.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ecmb.bdimg.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ecmc.bdimg.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,eduad.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,eiv.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,fclick.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,fclog.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,h2tcbox.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,hao123union.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,hm.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,hmma.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,imgstat.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,iwanad.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,miao.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,miaowu.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,mipcache.bdstatic.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,mobads.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,mobads-logs.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,mobads-pre-config.cdn.bcebos.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,mountain.zhidao.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,nsclick.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,nsclickvideo.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pimlog.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pos.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,sclick.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,spcode.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,tcbox.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ubmcvideo.baidustatic.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,union.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,unionimage.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,wangmeng.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,wkctj.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,wm.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,zz.bdstatic.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-WILDCARD,nadvideo*.baidu.com,REJECT-DROP,extended-matching,pre-matching
URL-REGEX,^http?:\/\/tiebac\.baidu\.com\/.*\/adLog,REJECT-DROP,extended-matching,pre-matching
URL-REGEX,^http?:\/\/tiebac\.baidu\.com\/.*\/video\/vlog,REJECT-DROP,extended-matching,pre-matching
# 百度广告与行为追踪
DOMAIN-SUFFIX,log.baidu.com,REJECT-DROP,extended-matching,pre-matching
# 百度贴吧广告&追踪
DOMAIN-SUFFIX,ps.beacon.baidu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,tiebaads.baidu.com,REJECT-DROP,extended-matching,pre-matching
# 百度App、地图、贴吧相关追踪
DOMAIN-SUFFIX,issuecdn.baidupcs.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,sv.baidu.com,REJECT-DROP,extended-matching,pre-matching
# Bilibili
DOMAIN-SUFFIX,cm.bilibili.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,dataflow.biliapi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ad.bilibili.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ads.bilibili.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,log.bilibili.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,live-trace.bilibili.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ad.track.bilibili.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,biligame.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,api.biligame.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-WILDCARD,*-api.biligame.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,game.bilibili.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,acgvideo.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,link.bilibili.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,stat.bilibili.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,acg.tv,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,show.bilibili.com,REJECT-DROP,extended-matching,pre-matching
# Bytedance
DOMAIN-SUFFIX,ad.toutiao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,byteadverts.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ctobsnssdk.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,dig.bdurl.net,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,extlog.snssdk.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,i.snssdk.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,is.snssdk.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,bds.snssdk.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,mcs.snssdk.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pangolin.snssdk.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pangolin-hl.snssdk.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pangolin-lf.snssdk.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pangolin-lq.snssdk.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pangolin-dsp-toutiao-b.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pangolin-dsp-toutiao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pangolin-sdk-toutiao-b.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pangolin-sdk-toutiao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pangolin-sdk-toutiao1.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,panplayable-toutiao-b.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,panplayable-toutiao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pglstatp-sdk-toutiao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pglstatp-snssdk-toutiao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,api-access.pangolin-sdk-toutiao1.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pglstatp-toutiao-b.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pglstatp-toutiao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,shoppingads.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ads3-normal-hl.zijieapi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,yt-adapter.bytedance.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,track.bytedance.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ads.bytedance.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,log.bytedance.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ad.douyin.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,log.douyin.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,sf3-ttcdn-tos.pstatp.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,log.zijieapi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-WILDCARD,pglstatp-*-toutiao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-WILDCARD,pglstatp-toutiao*.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-WILDCARD,pangolin-*-toutiao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-WILDCARD,pangolin-*-toutiao*.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-WILDCARD,pangolin-dsp-toutiao*.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-WILDCARD,pangolin-sdk-toutiao*.com,REJECT-DROP,extended-matching,pre-matching
# Carrotquest
DOMAIN-SUFFIX,api-eu.carrotquest.app,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,api-eu.carrotquest.io,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,api-ru.carrotquest.app,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,api-ru.carrotquest.io,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,api-secure.carrotquest.app,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,api-secure.carrottrack.app,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,api.carrotquest.app,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,api.carrotquest.io,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,api.carrottrack.app,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,api.dashly.app,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,api.dashlytrack.app,REJECT-DROP,extended-matching,pre-matching
# GamerSky
DOMAIN-SUFFIX,click.gamersky.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ja.gamersky.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ja1.gamersky.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ja2.gamersky.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,wmbd.gamersky.com,REJECT-DROP,extended-matching,pre-matching
# iqiyi
DOMAIN-SUFFIX,ad.m.iqiyi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,afp.iqiyi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,c.uaa.iqiyi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,cloudpush.iqiyi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,cupid.iqiyi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ifacelog.iqiyi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,mbdlog.iqiyi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,msg.video.qiyi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,msg2.video.qiyi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,policy.video.iqiyi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,data.video.ptqy.gitv.tv,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,sdk-cache.video.ptqy.gitv.tv,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,t7z.cupid.ptqy.gitv.tv,REJECT-DROP,extended-matching,pre-matching
# JD
DOMAIN-SUFFIX,ads-union.jd.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ads.union.jd.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,c-nfa.jd.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,cps.360buy.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,gia.jd.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,img-x.jd.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,jzt.jd.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,stat.m.jd.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,skdisplay.jd.com,REJECT-DROP,extended-matching,pre-matching
# Kuaishou
DOMAIN-SUFFIX,adbkwai.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adkwai.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adukwai.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,e.kuaishou.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,e.kuaishou.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,log-sdk.gifshow.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,wlog.kuaishou.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ad.kuaishou.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,gdfp.gifshow.com,REJECT-DROP,extended-matching,pre-matching
# 快手广告SDK
DOMAIN-SUFFIX,log-sdk.kuaishou.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,glog.kuaishou.com,REJECT-DROP,extended-matching,pre-matching
# 快手跟踪行为分析
DOMAIN-SUFFIX,analytics-sdk.kuaishou.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,apm.kuaishou.com,REJECT-DROP,extended-matching,pre-matching
# Kugou
DOMAIN-SUFFIX,ads.service.kugou.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adserviceretry.kglink.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adserviceretry.kugou.com,REJECT-DROP,extended-matching,pre-matching
# Letv
DOMAIN-SUFFIX,apple.www.letv.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ark.letv.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,dc.letv.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,g3.letv.com,REJECT-DROP,extended-matching,pre-matching
# Netease
DOMAIN-SUFFIX,a.youdao.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,admusicpic.music.126.net,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ads.music.126.net,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,analytics.163.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,crash.163.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,crashlytics.163.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,g.163.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,iadmat.nosdn.127.net,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,iadmatapk.nosdn.127.net,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,iadmusicmat.music.126.net,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,iadmusicmatvideo.music.126.net,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,sentry.music.163.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,iadmusicmat.music.163.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,iadmatmusic.music.163.com,REJECT-DROP,extended-matching,pre-matching
# Qihoo360
DOMAIN-SUFFIX,c.sayhi.360.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,fenxi.360.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,fenxi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,lianmeng.360.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,mediav.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,mvad.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,qhupdate.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,s.360.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,s.so.360.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,s.union.360.cn,REJECT-DROP,extended-matching,pre-matching
# Sina
DOMAIN-SUFFIX,ad.sina.com.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ad.us.sinaimg.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adbox.sina.com.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adimg.mobile.sina.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adimg.uve.weibo.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ads.sina.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,alitui.weibo.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,beacon.sina.com.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,biz.weibo.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,click.uve.mobile.sina.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,click.uve.weibo.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,log.mix.sina.com.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,log.sina.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,log2.sina.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,mixer.sina.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,p4p.sina.com.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,rs.sinajs.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,sa.sina.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,sbeacon.sina.com.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,sdkclick.mobile.sina.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,slog.sina.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,slog.sina.com.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,wapwbclick.mobile.sina.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,wbclick.mobile.sina.cn,REJECT-DROP,extended-matching,pre-matching
# Sohu
DOMAIN-SUFFIX,adnet.sohu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ads.sohu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adv-sv-show.focus.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adv-sv-stat.focus.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,assp.sohu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,bdu.focus.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,fpb.sohu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,imp.go.sohu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,m.aty.sohu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,p.aty.sohu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pv.hd.sohu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pv.sohu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,qpb.sohu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,qpb1.sohu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,reke.at.sohu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,track.sohu.com,REJECT-DROP,extended-matching,pre-matching
# Sogou
DOMAIN-SUFFIX,inte.sogou.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,inte.sogoucdn.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,lu.sogoucdn.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pb.i.sogou.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,theta.sogoucdn.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,uranus.sogou.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,wuliao.epro.sogou.com,REJECT-DROP,extended-matching,pre-matching
# Tencent
DOMAIN-SUFFIX,apdcdn.tc.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,tsbdy.gtimg.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,admaterial.gdtimg.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,gdtimg.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,qzs.gdtimg.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,union.gdtimg.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adnet.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,report.gdtimg.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,sdk.gdtimg.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ads.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,tracking.gdtimg.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,win.gdt.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,xc.gdt.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,rpt.gdt.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,c2.gdt.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adsmind.gdtimg.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adsfile.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adsmind.ugdtimg.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,xs.l.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,canvas-cdn.gdt.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ad.browser.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ad.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ad.qun.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ad.tencentmusic.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ad.weixin.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adfilter.imtt.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,wxsnsdy.tc.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,wxsnsad.tc.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,wxs.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,wxa.wxs.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,wximg.wxs.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,wxsmw.wxs.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,wxsnsdy.wxs.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,wxsnsdythumb.wxs.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,wxsmsdy.video.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN,cube.weixinbridge.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adping.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adpm.app.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adsclick.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adshmmsg.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adslvfile.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adslvseed.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adsmind.apdcdn.tc.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adsqqclick.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adstats.tencentmusic.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adstestview.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adsview.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adsview2.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adv.app.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adver.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,beacon.cdn.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,beacon.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,beaconcdn.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,btrace.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,bugly.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,e.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,gdt.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,hq-tracking.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,htrace.wetvinfo.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,isdspeed.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,log.tbs.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,mdt.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,monitor.music.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,monitor.uu.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,mpush.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,mtrace.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pgdt.gtimg.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pingjs.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pmir.3g.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,push.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,qqdata.ab.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,report.qqweb.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,report.tencentmusic.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,rmonitor.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,sngmta.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,stat.y.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,tajs.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,tcss.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,tmead.y.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,tmeadcomm.y.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,tpstelemetry.tencent.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,trace.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ugdtimg.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,wit.qq.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,wa.gtimg.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,tdsdk.cpatrk.net,REJECT-DROP,extended-matching,pre-matching
# Xiaomi
DOMAIN-SUFFIX,a.market.xiaomi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ad.intl.xiaomi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ad.mi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ad.xiaomi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ad1.xiaomi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,admob.xiaomi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adv.sec.intl.miui.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adv.sec.miui.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,data.mistat.india.xiaomi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,data.mistat.intl.xiaomi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,data.mistat.rus.xiaomi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,data.mistat.xiaomi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,logupdate.avlyun.sec.miui.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,misc.in.duokanbox.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,sentry.d.mi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,sentry.d.xiaomi.net,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,stats.music.xiaomi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,tjqonline.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,tracker.ai.xiaomi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,webtrack.ad.intl.xiaomi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,tracker.xiaomixiaoai.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,tracking.miui.com,REJECT-DROP,extended-matching,pre-matching
#DOMAIN-WILDCARD,ad*.xiaomi.com
#DOMAIN-WILDCARD,ad*.mi.com
# Youku
DOMAIN-SUFFIX,ad.api.3g.youku.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ad.api.mobile.youku.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ad.mobile.youku.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adashx.ut.youku.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,atm.youku.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,e.stat.ykimg.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ems.youku.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,guanggaoad.youku.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,h-adashx.ut.youku.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,lstat.youku.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,mobilemsg.youku.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,msg.youku.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,p-log.ykimg.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,passport-log.youku.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pl.youku.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,s-adashx.ut.youku.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,stat.youku.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,statis.api.3g.youku.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,v6-adashx.ut.youku.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,yk-ssp.ad.youku.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ykad-data.youku.com,REJECT-DROP,extended-matching,pre-matching
# Zhihu
DOMAIN-SUFFIX,crash2.zhihu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,zhihu-web-analytics.zhihu.com,REJECT-DROP,extended-matching,pre-matching
# XMind
DOMAIN-WILDCARD,api*.xmind.net,REJECT-DROP,extended-matching,pre-matching
DOMAIN-WILDCARD,api*.xmind.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,api.xmind.net,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,api2.xmind.net,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,api.xmind.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,api2.xmind.cn,REJECT-DROP,extended-matching,pre-matching
# XMind云端存储与同步
DOMAIN-SUFFIX,cloud.xmind.net,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,cloud.xmind.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,sync-api.xmind.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,sync.xmind.cn,REJECT-DROP,extended-matching,pre-matching
# XMind日志与埋点
DOMAIN-SUFFIX,tracking.xmind.net,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,tracking.xmind.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,log.xmind.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,log-api.xmind.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-WILDCARD,log*.xmind.cn,REJECT-DROP,extended-matching,pre-matching
# XMind其他可能的广告资源
DOMAIN-SUFFIX,ads.xmind.net,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ads.xmind.cn,REJECT-DROP,extended-matching,pre-matching
# 小红书
DOMAIN-SUFFIX,ads-i4.xhscdn.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,tracklog.xhs.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,referee.xiaohongshu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,log.xiaohongshu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,mus.xiaohongshu.com,REJECT-DROP,extended-matching,pre-matching
# 广告投送
DOMAIN-SUFFIX,ad.xiaohongshu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ad.xhs.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,material.xhs.cn,REJECT-DROP,extended-matching,pre-matching
# 美团、滴滴广告
DOMAIN-SUFFIX,ad.meituan.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ad.didi.com,REJECT-DROP,extended-matching,pre-matching
# 拼多多
DOMAIN-SUFFIX,adim.pinduoduo.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,api.pinduoduo.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-WILDCARD,*-dsp.pinduoduo.com,REJECT-DROP,extended-matching,pre-matching
# 科大讯飞
DOMAIN-SUFFIX,log.iflytek.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,scs.iflytek.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,log.voicecloud.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,log1.voicecloud.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,log2.voicecloud.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-WILDCARD,log*.voicecloud.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,config.voicecloud.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,logservice.voicecloud.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,iflyad.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,tracking.voicecloud.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,mobilelog.voicecloud.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,apptrace.voicecloud.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,mystat.voicecloud.cn,REJECT-DROP,extended-matching,pre-matching
# 讯飞广告拦截规则
DOMAIN-SUFFIX,ad.voicecloud.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,stat.voicecloud.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adplus.voicecloud.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adse.voicecloud.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ad.voice.voicecloud.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,da.voicecloud.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,gg.voicecloud.cn,REJECT-DROP,extended-matching,pre-matching
# 多玩YY
DOMAIN-SUFFIX,stat.duowan.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ads.duowan.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,tracking.duowan.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,monitor.duowan.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,duowan.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,zhuiya.yy.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ab.yy.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-WILDCARD,zhuiya.*cdn.yy.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,myzhiniu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,bd-flv.yy.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,gslb.yy.com,REJECT-DROP,extended-matching,pre-matching
# YY# 行为分析
DOMAIN-SUFFIX,stat.yy.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ad.yy.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,trace.yy.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adlog.yy.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,oplog.yy.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-WILDCARD,*log.yy.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,union-feedback.yy.com,REJECT-DROP,extended-matching,pre-matching
# 虎牙广告
DOMAIN-SUFFIX,ad.huya.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adeng.huya.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adttl.huya.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,baizhanlive.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,bigda.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,argoapi.yy.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,data.3g.yy.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-WILDCARD,data.*.yy.com,REJECT-DROP,extended-matching,pre-matching
# 虎牙用户行为追踪
DOMAIN-SUFFIX,tracking.huya.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,report.huya.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,logstatic.huya.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,analysis.huya.com,REJECT-DROP,extended-matching,pre-matching
# 虎牙开屏广告
DOMAIN-SUFFIX,assetsdw.huya.com,REJECT-DROP,extended-matching,pre-matching
# 斗鱼直播广告
DOMAIN-SUFFIX,ads.douyucdn.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,log.douyucdn.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,analytics.douyu.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,push.douyu.com,REJECT-DROP,extended-matching,pre-matching
# 斗鱼直播弹幕监控分析
DOMAIN-SUFFIX,zhibo.douyucdn.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,reportlog.douyucdn.cn,REJECT-DROP,extended-matching,pre-matching
# 华为
#DOMAIN-SUFFIX,dbankcloud.cn
DOMAIN-SUFFIX,metrics.data.hicloud.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,logservice.hicloud.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,grs.hicloud.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN,metrics1.data.hicloud.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN,metrics3.data.hicloud.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN,logbak.hicloud.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN,log1.c.hicloud.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN,configdl.hicloud.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN,connect-drcn.dbankcloud.cn,REJECT-DROP,extended-matching,pre-matching
# 华为广告推送相关
DOMAIN-WILDCARD,ads*.hicloud.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ads.hicloud.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ads01.hicloud.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,huaweiads.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,hispace.hicloud.com,REJECT-DROP,extended-matching,pre-matching
# 金山
DOMAIN-SUFFIX,ads.wps.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,log.wps.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,update.wps.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,flow.wps.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,push.wps.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,tongji.wps.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,push.wps.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,android.push.wps.cn,REJECT-DROP,extended-matching,pre-matching
# 金山毒霸
DOMAIN-SUFFIX,stat.kxjj.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,stat.ksosoft.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,push.ksosoft.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ad.ksosoft.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,news.ksosoft.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pkg.ksosoft.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,dl.ksosoft.com,REJECT-DROP,extended-matching,pre-matching
# 猎豹清理大师
DOMAIN-SUFFIX,ads.cmcm.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,tracking.cmcm.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,log.cmcm.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,inapp.cmcm.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,analytics.cmcm.com,REJECT-DROP,extended-matching,pre-matching
# 中国移动
DOMAIN-SUFFIX,ad.cmvideo.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,wap.cmread.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ads.miguvideo.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,log.miguvideo.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ad.api.10086.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,mon.10086.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,collect.10086.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adinf.xj.chinamobile.com,REJECT-DROP,extended-matching,pre-matching
# 中国电信
DOMAIN-SUFFIX,open.e.189.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,imarket.189.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ad.189.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ums.189.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,sta.telecom.com.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,app.189.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ysten.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,cqccn.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,bigdata-behaviordata.189.cn,REJECT-DROP,extended-matching,pre-matching
# 中国联通
DOMAIN-SUFFIX,ad.wo.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adlog.wo.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,analytics.wo.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adserver.wo.cn,REJECT-DROP,extended-matching,pre-matching
# ads
DOMAIN-SUFFIX,51.la,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,51y5.net,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,a.adtng.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,aaxads.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ad-srv.net,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ad.api.moji.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ad.wang502.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adbutter.net,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,addthisedge.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ads.huan.tv,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ads.huantest.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ads.trafficjunky.net,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ads.wteam.xyz,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adservice.sigmob.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adtechus.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adtrue.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adxprtz.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,cdn.advertserve.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,cdn.banclip.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,cfts1tifqr.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,contentabc.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,cretgate.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,data.flurry.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,decide.mixpanel.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,emogi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ero-advertising.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,eroadvertising.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,evt.mxplay.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,exoclick.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,exosrv.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,go2.global,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,gozendata.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,gz-data.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,gzads.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,img-bss.csdn.net,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,imglnkc.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,imglnkd.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,inner-active.mobi,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,innovid.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,jads.co,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,jl3.yjaxa.top,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,js-agent.newrelic.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,juicyads.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,kepler-37b.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,leanplum.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,lqc006.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,moat.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,moatads.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,mob.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,mobwithad.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,mopub.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,onesignal.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,realsrv.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,s4yxaqyq95.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,shhs-ydd8x2.yjrmss.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ssp.api.tappx.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,static.hotjar.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,static.javhd.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,tm-banners.gamingadult.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,trafficfactory.biz,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,tsyndicate.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,uberads.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,wwads.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,xdplt.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ad.ximalaya.com,REJECT-DROP,extended-matching,pre-matching
# ads-all
DOMAIN-SUFFIX,1rx.io,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,7box.vip,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ad-delivery.net,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adcolony.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adinplay.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adnxs.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,advertserve.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adview.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,casalemedia.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,contextual.media.net,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,cpmstar.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,demdex.net,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,httpool.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,lijit.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,mfadsrvr.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,mgid.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ns1p.net,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,sigmob.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,spotxchange.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,unimhk.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,upapi.net,REJECT-DROP,extended-matching,pre-matching
# 12306
DOMAIN-SUFFIX,ad.12306.cn,REJECT-DROP,extended-matching,pre-matching
# 36Kr
DOMAIN-SUFFIX,adx.36kr.com,REJECT-DROP,extended-matching,pre-matching
# AdHub
DOMAIN-SUFFIX,hubcloud.com.cn,REJECT-DROP,extended-matching,pre-matching
# AdScope
DOMAIN-SUFFIX,beizi.biz,REJECT-DROP,extended-matching,pre-matching
# ali213
DOMAIN-SUFFIX,click.ali213.net,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pbmp.ali213.net,REJECT-DROP,extended-matching,pre-matching
# AppLovin
DOMAIN-SUFFIX,applovin.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,applvn.com,REJECT-DROP,extended-matching,pre-matching
# Caixin
DOMAIN-WILDCARD,pinggai*.caixin.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pinggai0.caixin.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pinggai1.caixin.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pinggai2.caixin.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pinggai3.caixin.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pinggai4.caixin.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pinggai5.caixin.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pinggai6.caixin.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pinggai7.caixin.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pinggai8.caixin.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pinggai9.caixin.com,REJECT-DROP,extended-matching,pre-matching
# Chinaso
DOMAIN-SUFFIX,adq.chinaso.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,stat.chinaso.com,REJECT-DROP,extended-matching,pre-matching
# hiido
DOMAIN-SUFFIX,mlog.hiido.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ylog.hiido.com,REJECT-DROP,extended-matching,pre-matching
# hpply
DOMAIN-SUFFIX,ad.hpplay.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adc.hpplay.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adeng.hpplay.cn,REJECT-DROP,extended-matching,pre-matching
# Httpool
DOMAIN-SUFFIX,toboads.com,REJECT-DROP,extended-matching,pre-matching
# ironSource# Atom
DOMAIN-SUFFIX,analytics-data.io,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,atom-data.io,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ironbeast.io,REJECT-DROP,extended-matching,pre-matching
# joyplus
DOMAIN-SUFFIX,advapi.joyplus.tv,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,advapikj.joyplus.tv,REJECT-DROP,extended-matching,pre-matching
# pocoiq
DOMAIN-SUFFIX,cdn.pocoiq.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,oct.pocoiq.cn,REJECT-DROP,extended-matching,pre-matching
# Qiniu
DOMAIN-SUFFIX,dn-growing.qbox.me,REJECT-DROP,extended-matching,pre-matching
# tagtic
DOMAIN-SUFFIX,g1.tagtic.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,xy-log.tagtic.cn,REJECT-DROP,extended-matching,pre-matching
# UNI# Marketing
DOMAIN-SUFFIX,ad.unimhk.com,REJECT-DROP,extended-matching,pre-matching
# UCloud
DOMAIN-SUFFIX,das-rpt-log.ucloud.cn,REJECT-DROP,extended-matching,pre-matching
# 数字精准广告
DOMAIN-SUFFIX,telecome.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,unioncom.cc,REJECT-DROP,extended-matching,pre-matching
# 亿帆广告
DOMAIN-SUFFIX,yfanads.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,yfanads.com,REJECT-DROP,extended-matching,pre-matching
# 数字联盟
DOMAIN-SUFFIX,shuzilm.cn,REJECT-DROP,extended-matching,pre-matching
# 中国广告协会CAID
DOMAIN-SUFFIX,china-caa.org,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,cnaa123.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,chinaciaf.org,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,iabchina.cn,REJECT-DROP,extended-matching,pre-matching
# 卓信id
DOMAIN-SUFFIX,zxid-api.mobileservice.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,zxid-m.mobileservice.cn,REJECT-DROP,extended-matching,pre-matching
# 深演智能
DOMAIN-SUFFIX,ipinyou.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ipinyou.com.cn,REJECT-DROP,extended-matching,pre-matching
# 智云众# OptAim
DOMAIN-SUFFIX,optaim.com,REJECT-DROP,extended-matching,pre-matching
# 加和科技# AddNewer
DOMAIN-SUFFIX,reachmax.cn,REJECT-DROP,extended-matching,pre-matching
# 热云数据
DOMAIN-SUFFIX,reyun.com,REJECT-DROP,extended-matching,pre-matching
# 神策数据
DOMAIN-SUFFIX,static.sensorsdata.cn,REJECT-DROP,extended-matching,pre-matching
# 诸葛io
DOMAIN-SUFFIX,zhugeapi.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,zhugeapi.net,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,zhugeio.com,REJECT-DROP,extended-matching,pre-matching
# 酷云互动
DOMAIN-SUFFIX,kuyun.com,REJECT-DROP,extended-matching,pre-matching
# 车来了
DOMAIN-SUFFIX,atrace.chelaile.net.cn,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,ad.chelaile.net.cn,REJECT,extended-matching,pre-matching
DOMAIN-SUFFIX,logs.chelaile.net.cn,REJECT,extended-matching,pre-matching
# 航旅纵横
DOMAIN-SUFFIX,analytics.umetrip.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,sensors.umetrip.com.cn,REJECT-DROP,extended-matching,pre-matching


DOMAIN-SUFFIX,dns.xiaomi.net,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,tracking.miui.com,REJECT-DROP,extended-matching,pre-matching

DOMAIN-SUFFIX,detect.sms.360.cn,REJECT-DROP,extended-matching,pre-matching

DOMAIN-SUFFIX,ads.95516.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adsfilebssdlbig.ali.kugou.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,po.funshion.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,e.cn.miaozhen.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,adsebs.ximalaya.com,REJECT-DROP,extended-matching,pre-matching
