#!name=CA_Block
#!desc=某些规则要清除缓存或者重新安装APP，拦截广告才会生效！

[Rule]
#TrustwaveCA（美国，曾提供监听型中间证书）
DOMAIN-SUFFIX,trustwave.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ocsp.trustwave.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,crl.trustwave.com,REJECT-DROP,extended-matching,pre-matching

#TrustCorSystems（巴拿马，关联美国情报承包商）
DOMAIN-SUFFIX,trustcor.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ocsp.trustcor.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,crl.trustcor.com,REJECT-DROP,extended-matching,pre-matching

#DigiNotar（荷兰，遭黑客攻破并伪造*.google.com证书）
DOMAIN-SUFFIX,diginotar.nl,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ocsp.diginotar.nl,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,crl.diginotar.nl,REJECT-DROP,extended-matching,pre-matching

#TurkTrust（土耳其，曾签发伪造中间证书，攻击案例确凿）
DOMAIN-SUFFIX,turktrust.com.tr,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ocsp.turktrust.com.tr,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,crl.turktrust.com.tr,REJECT-DROP,extended-matching,pre-matching

#WoSign（中国，签发非法证书，已遭全平台吊销）
DOMAIN-SUFFIX,wosign.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ocsp.wosign.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,crl.wosign.com,REJECT-DROP,extended-matching,pre-matching

#StartCom（原以色列，已被WoSign收购，信任已被撤销）
DOMAIN-SUFFIX,startssl.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ocsp.startssl.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,crl.startssl.com,REJECT-DROP,extended-matching,pre-matching

#GFW‑related:GeedgeNetworks
DOMAIN-SUFFIX,geedgenetworks.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ocsp.geedgenetworks.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,crl.geedgenetworks.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,tsg.geedgenetworks.com,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,cybernarrator.geedgenetworks.com,REJECT-DROP,extended-matching,pre-matching

#GFW‑related:MESA项目
DOMAIN-SUFFIX,mesalab.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,ocsp.mesalab.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,crl.mesalab.cn,REJECT-DROP,extended-matching,pre-matching
DOMAIN-SUFFIX,pki.iie.ac.cn,REJECT-DROP,extended-matching,pre-matching